version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
  pgbouncer172:
    build:
      context: .
      args:
        pgbversion: 1.7.2
    volumes:
      - .:/vol
    links:
      - postgres
    ports:
      - 6432:6432
  pgbouncer1901120:
    build:
      context: .
      args:
        pgbversion: 1.9.0
    volumes:
      - .:/vol
    links:
      - pgbouncer1120
    ports:
      - 6433:6432
    environment:
      - PGBOUNCER_INI_PATH=/vol/pgbouncer2.ini
  pgbouncer1120:
    build:
      context: .
      args:
        pgbversion: 1.12.0
    volumes:
      - .:/vol
    links:
      - postgres
    ports:
      - 6434:6432
  pgbouncer1120_2:
    build:
      context: .
      args:
        pgbversion: 1.12.0
    volumes:
      - .:/vol
    links:
      - pgbouncer1120
    ports:
      - 6435:6432
    environment:
      - PGBOUNCER_INI_PATH=/vol/pgbouncer2.ini
